site_name: GBVEQ - Documentation

plugins:
    - search
    - i18n:
        languages:
            - locale: es
              name: Español
              build: true
              nav_translations:
                Home: Inicio
                Tables: Tablas
            - locale: en
              default: true
              name: English
              build: true

theme:
    name: material

nav:
    - Home: index.md
    - Tables:
        - violencia_genero:
            - feminicidios_pareja_expareja: Tables/violencia_genero/feminicidios_pareja_expareja.md
            - feminicidios_fuera_pareja_expareja: Tables/violencia_genero/feminicidios_fuera_pareja_expareja.md
            - menores_victimas_mortales: Tables/violencia_genero/menores_victimas_mortales.md
            - servicio_016: Tables/violencia_genero/servicio_016.md
            - usuarias_atenpro: Tables/violencia_genero/usuarias_atenpro.md
            - dispositivos_electronicos_seguimiento: Tables/violencia_genero/dispositivos_electronicos_seguimiento.md
            - ayudas_articulo_27: Tables/violencia_genero/ayudas_articulo_27.md
            - viogen: Tables/violencia_genero/viogen.md
            - autorizaciones_residencia_trabajo_vvg: Tables/violencia_genero/autorizaciones_residencia_trabajo_vvg.md
            - denuncias_vg_pareja: Tables/violencia_genero/denuncias_vg_pareja.md
            - denuncias_vg_presentadas: Tables/violencia_genero/denuncias_vg_presentadas.md
            - infracciones_penales_inputadas_vg: Tables/violencia_genero/infracciones_penales_inputadas_vg.md
            - ordenes_proteccion: Tables/violencia_genero/ordenes_proteccion.md
            - renta_activa_insercion: Tables/violencia_genero/renta_activa_insercion.md
            - contratos_bonificados_sustitucion: Tables/violencia_genero/contratos_bonificados_sustitucion.md
            - ayudas_cambio_residencia: Tables/violencia_genero/ayudas_cambio_residencia.md
            - encuesta_europea_2022: Tables/violencia_genero/encuesta_europea_2022.md
            - macroencuesta_2019: Tables/violencia_genero/macroencuesta_2019.md
            - macroencuesta_2015: Tables/violencia_genero/macroencuesta_2015.md
            - macroencuesta_2011: Tables/violencia_genero/macroencuesta_2011.md
            - fusion_encuestas: Tables/violencia_genero/fusion_encuestas.md
        - demografia:
            - poblacion_municipio: Tables/demografia/poblacion_municipios.md
            - poblacion_grupo_edad: Tables/demografia/poblacion_grupo_edad.md
            - matrimonios_heterosexuales: Tables/demografia/matrimonios_heterosexuales.md
            - matrimonios_homosexuales: Tables/demografia/matrimonios_homosexuales.md
            - tasa_divorcialidad: Tables/demografia/tasa_divorcialidad.md
            - divorcios_segun_duracion_matrimonio: Tables/demografia/divorcios_segun_duracion_matrimonio.md
            - nulidades_separaciones_divorcios: Tables/demografia/nulidades_separaciones_divorcios.md
            - hogares_monoparentales: Tables/demografia/hogares_monoparentales.md
        - igualdad_formal:
            - eige_dominios: Tables/igualdad_formal/eige_dominios.md
            - eige_indicadores: Tables/igualdad_formal/eige_indicadores.md
            - eige_interseccionalidades: Tables/igualdad_formal/eige_interseccionalidades.md
            - eige_violencia: Tables/igualdad_formal/eige_violencia.md
            - ganancia_por_hora_trabajo: Tables/igualdad_formal/ganancia_por_hora_trabajo.md
            - mujeres_cargos_autonomicos: Tables/igualdad_formal/mujeres_cargos_autonomicos.md
        - politicas_publicas_igualdad_violencia:
            - legislacion: Tables/politicas_publicas_igualdad_violencia/legislacion.md
            - institutos_mujer: Tables/politicas_publicas_igualdad_violencia/institutos_mujer.md
            - centros_acogida_emergencia: Tables/politicas_publicas_igualdad_violencia/centros_acogida_emergencia.md
        - educacion_juventud:
            - excedencias_cuidado_hijos_familiares: Tables/educacion_juventud/excedencias_cuidado_hijos_familiares.md
            - prestaciones_nacimiento_y_cuidado_menor: Tables/educacion_juventud/prestaciones_nacimiento_y_cuidado_menor.md
            - prestaciones_maternidad_paternidad: Tables/educacion_juventud/prestaciones_maternidad_paternidad.md
            - matriculados_educacion_no_universitaria: Tables/educacion_juventud/matriculados_educacion_no_universitaria.md
            - matriculados_universidad: Tables/educacion_juventud/matriculados_universidad.md
            - egresados_universidad: Tables/educacion_juventud/egresados_universidad.md
            - nivel_formacion: Tables/educacion_juventud/nivel_formacion.md
        - migracion:
            - residentes_extranjeros: Tables/migracion/residentes_extranjeros.md
        - tecnologia_y_medios:
            - acceso_internet_viviendas: Tables/tecnologia_y_medios/acceso_internet_viviendas.md
            - uso_internet_personas: Tables/tecnologia_y_medios/uso_internet_personas.md
            - uso_internet_ninios: Tables/tecnologia_y_medios/uso_internet_ninios.md
            - usuarios_redes_sociales: Tables/tecnologia_y_medios/usuarios_redes_sociales.md
        - percepcion_social:
            - barometros_generales: Tables/percepcion_social/barometros_generales.md
            - encuesta_igualdad_2023: Tables/percepcion_social/encuesta_igualdad_2023.md
            - encuesta_violencia_sexual_2023: Tables/percepcion_social/encuesta_violencia_sexual_2023.md
            - encuesta_violencia_sexual_2017: Tables/percepcion_social/encuesta_violencia_sexual_2017.md
            - encuesta_violencia_genero_juventud_2013: Tables/percepcion_social/encuesta_violencia_genero_juventud_2013.md
            - encuesta_violencia_genero_2012: Tables/percepcion_social/encuesta_violencia_genero_2012.md
        - economia_laboral:
            - tasa_actividad_paro_empleo: Tables/economia_laboral/tasa_actividad_paro_empleo.md
            - riesgo_pobreza_exclusion: Tables/economia_laboral/riesgo_pobreza_exclusion.md
        - seguridad_criminalidad:
            - tasas_homicidios_criminalidad: Tables/seguridad_criminalidad/tasas_homicidios_criminalidad.md
            - delitos_sexuales: Tables/seguridad_criminalidad/delitos_sexuales.md
        - politica:
            - elecciones_congreso: Tables/politica/elecciones_congreso.md
            - elecciones_parlamentos_autonomicos: Tables/politica/elecciones_parlamentos_autonomicos.md
            - presidentes_espania: Tables/politica/presidentes_espania.md
            - presidentes_autonomicos: Tables/politica/presidentes_autonomicos.md
        - geo:
            - comunidades_autonomas: Tables/geo/comunidades_autonomas.md
            - provincias: Tables/geo/provincias.md
            - municipios: Tables/geo/municipios.md
            - paises: Tables/geo/paises.md
        - metadata:
            - fuentes: Tables/metadata/fuentes.md
            - fuentes_tablas: Tables/metadata/fuentes_tablas.md
