import csv
from pathlib import Path

MUNICIPIOS_PATH = Path("data") / "clean" / "geo" / "municipios.csv"


def _load_municipios_dict() -> dict[int, dict[str, int]]:
    """Load municipios data keyed by provincia id"""
    municipios_dict: dict[int, dict[str, int]] = {}
    with open(MUNICIPIOS_PATH, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter=";")  # type: ignore
        for row in reader:  # type: ignore
            provincia_id = int(row["provincia_id"])  # type: ignore
            municipio_name = row["nombre"].strip()  # type: ignore
            municipio_id = int(row["municipio_id"])  # type: ignore
            prov_dict = municipios_dict.setdefault(provincia_id, {})
            prov_dict.setdefault(municipio_name, municipio_id)  # type: ignore

            # Special case "/" (Arrasate/Mondragón)
            slash_variants = [part.strip() for part in municipio_name.split("/")]
            for variant in slash_variants:
                prov_dict.setdefault(variant, municipio_id)
                # Nested special case "/" and "," (Alqueries, les/Alquerías del Niño Perdido)
                if "," in variant:
                    base, article = [s.strip() for s in variant.split(",", 1)]
                    prov_dict.setdefault(base, municipio_id)
                    prov_dict.setdefault(f"{base} ({article})", municipio_id)

            # Special case "," (Jonquera, La)
            if "," in municipio_name and len(slash_variants) == 1:
                base, article = [s.strip() for s in municipio_name.split(",", 1)]
                prov_dict.setdefault(base, municipio_id)
                prov_dict.setdefault(f"{base} ({article})", municipio_id)
    return municipios_dict


DICT_MUNICIPIOS: dict[int, dict[str, int]] = _load_municipios_dict()

DICT_UNKNOWN_STRINGS = {
    "",
    "unknown",
    "n/c",
    "no consta",
    "noconsta",
    "desconocida",
}

DICT_MONTHS = {
    "Enero": 1,
    "Febrero": 2,
    "Marzo": 3,
    "Abril": 4,
    "Mayo": 5,
    "Junio": 6,
    "Julio": 7,
    "Agosto": 8,
    "Septiembre": 9,
    "Octubre": 10,
    "Noviembre": 11,
    "Diciembre": 12,
}

DICT_QUARTER = {
    "primero": 1,
    "segundo": 2,
    "tercero": 3,
    "cuarto": 4,
}

DICT_COMUNIDADES_AUTOMAS = {
    "Total nacional": 0,
    "Total": 0,
    "España": 0,
    "Andalucía": 1,
    "Aragón": 2,
    "Asturias": 3,
    "Principado de Asturias": 3,
    "Asturias, Principado de": 3,
    "Asturias (Principado de)": 3,
    "Asturias (Ppdo. de)": 3,
    "Islas Baleares": 4,
    "Illes Balears": 4,
    "Balears, Illes": 4,
    "Baleares, Illes": 4,
    "Balears (Illes)": 4,
    "Baleares": 4,
    "Islas Canarias": 5,
    "Canarias": 5,
    "Cantabria": 6,
    "Castilla y León": 7,
    "Castilla-La Mancha": 8,
    "Castilla La Mancha": 8,
    "Cataluña": 9,
    "Comunitat Valenciana": 10,
    "Comunidad Valenciana": 10,
    "Com. Valenciana": 10,
    "C. Valenciana": 10,
    "Extremadura": 11,
    "Galicia": 12,
    "Comunidad de Madrid": 13,
    "Madrid": 13,
    "Madrid (Comunidad de)": 13,
    "Madrid, Comunidad de": 13,
    "Madrid (Com. de)": 13,
    "Región de Murcia": 14,
    "Murcia, Región de": 14,
    "Murcia (Región de)": 14,
    "Murcia": 14,
    "Comunidad Foral de Navarra": 15,
    "Navarra (Com. Foral de)": 15,
    "Navarra": 15,
    "Navarra (Comunidad Foral de)": 15,
    "Navarra, Comunidad Foral de": 15,
    "País Vasco": 16,
    "Euskadi": 16,
    "País Vasco/Euskadi": 16,
    "Euskadi/País Vasco": 16,
    "País Vasco (Euskadi)": 16,
    "Euskadi (País Vasco)": 16,
    "La Rioja": 17,
    "Rioja (La)": 17,
    "Rioja, La": 17,
    "Rioja": 17,
    "Ceuta": 18,
    "Ceuta (Ciudad Autónoma de)": 18,
    "Melilla": 19,
    "Melilla (Ciudad Autónoma de)": 19,
}


DICT_PROVINCIAS = {
    "Araba/Álava": 1,
    "Araba-Álava": 1,
    "Álava": 1,
    "Araba": 1,
    "Albacete": 2,
    "Alicante/Alacant": 3,
    "Alicante": 3,
    "Alacant": 3,
    "Almería": 4,
    "Ávila": 5,
    "Badajoz": 6,
    "Balears, Illes": 7,
    "Balears (Illes)": 7,
    "Illes Balears": 7,
    "Baleares": 7,
    "Balears": 7,
    "Barcelona": 8,
    "Burgos": 9,
    "Cáceres": 10,
    "Cádiz": 11,
    "Castellón/Castelló": 12,
    "Castellón de la Plana": 12,
    "Castelló": 12,
    "Castellón": 12,
    "Cast. de la Plana": 12,
    "Ciudad Real": 13,
    "Córdoba": 14,
    "A Coruña": 15,
    "Coruña (A)": 15,
    "Coruña, A": 15,
    "La Coruña": 15,
    "Cuenca": 16,
    "Girona": 17,
    "Gerona": 17,
    "Granada": 18,
    "Guadalajara": 19,
    "Gipuzkoa": 20,
    "Guipúzcoa": 20,
    "Huelva": 21,
    "Huesca": 22,
    "Jaén": 23,
    "León": 24,
    "Lleida": 25,
    "Lérida": 25,
    "Rioja (La)": 26,
    "La Rioja": 26,
    "Rioja": 26,
    "Rioja, La": 26,
    "Lugo": 27,
    "Madrid": 28,
    "Málaga": 29,
    "Murcia": 30,
    "Navarra": 31,
    "Ourense": 32,
    "Orense": 32,
    "Asturias": 33,
    "Asturias/Asturies": 33,
    "Asturies": 33,
    "Palencia": 34,
    "Palmas (Las)": 35,
    "Las Palmas": 35,
    "Palmas": 35,
    "Palmas, Las": 35,
    "Pontevedra": 36,
    "Salamanca": 37,
    "Santa Cruz de Tenerife": 38,
    "Sta. Cruz de Tenerife": 38,
    "Sta. Cruz Tenerife": 38,
    "Tenerife": 38,
    "Cantabria": 39,
    "Segovia": 40,
    "Sevilla": 41,
    "Soria": 42,
    "Tarragona": 43,
    "Teruel": 44,
    "Toledo": 45,
    "Valencia/València": 46,
    "Valencia": 46,
    "València": 46,
    "Valladolid": 47,
    "Bizkaia": 48,
    "Vizcaya": 48,
    "Zamora": 49,
    "Zaragoza": 50,
    "Ceuta": 51,
    "Melilla": 52,
}

DICT_NATIONALITIES = {
    "Otro": "Otros",
    "Otra": "Otros",
    "Otras nacionalidades": "Otros",
    "Extranjera": "Otros",
    "Extranjero": "Otros",
    "Afganistán": "Afganistán",
    "afgano": "Afganistán",
    "afgana": "Afganistán",
    "Albania": "Albania",
    "albanés": "Albania",
    "albanesa": "Albania",
    "Alemania": "Alemania",
    "alemán": "Alemania",
    "alemana": "Alemania",
    "Andorra": "Andorra",
    "andorrano": "Andorra",
    "andorrana": "Andorra",
    "Angola": "Angola",
    "angoleño": "Angola",
    "angoleña": "Angola",
    "Antigua y Barbuda": "Antigua y Barbuda",
    "antiguano": "Antigua y Barbuda",
    "antiguana": "Antigua y Barbuda",
    "Arabia Saudita": "Arabia Saudita",
    "Arabia Saudí": "Arabia Saudita",
    "saudí": "Arabia Saudita",
    "Argelia": "Argelia",
    "argelino": "Argelia",
    "argelina": "Argelia",
    "Argentina": "Argentina",
    "argentino": "Argentina",
    "argentina": "Argentina",
    "Armenia": "Armenia",
    "armenio": "Armenia",
    "armenia": "Armenia",
    "Australia": "Australia",
    "australiano": "Australia",
    "australiana": "Australia",
    "Austria": "Austria",
    "austriaco": "Austria",
    "austriaca": "Austria",
    "Azerbaiyán": "Azerbaiyán",
    "azerbaiyano": "Azerbaiyán",
    "azerbaiyana": "Azerbaiyán",
    "Bahamas": "Bahamas",
    "bahameño": "Bahamas",
    "bahameña": "Bahamas",
    "Bangladesh": "Bangladés",
    "Bangladés": "Bangladés",
    "bangladesí": "Bangladés",
    "Barbados": "Barbados",
    "barbadense": "Barbados",
    "Baréin": "Baréin",
    "bareiní": "Baréin",
    "Bélgica": "Bélgica",
    "belga": "Bélgica",
    "Belice": "Belice",
    "beliceño": "Belice",
    "beliceña": "Belice",
    "Benín": "Benín",
    "beninés": "Benín",
    "beninesa": "Benín",
    "Bielorrusia": "Bielorrusia",
    "bielorruso": "Bielorrusia",
    "bielorrusa": "Bielorrusia",
    "Birmania": "Birmania",
    "birmano": "Birmania",
    "birmana": "Birmania",
    "Myanmar": "Birmania",
    "Bolivia": "Bolivia",
    "boliviano": "Bolivia",
    "boliviana": "Bolivia",
    "Bosnia y Herzegovina": "Bosnia y Herzegovina",
    "bosnio": "Bosnia y Herzegovina",
    "bosnia": "Bosnia y Herzegovina",
    "Bosnia-Herzegovina": "Bosnia y Herzegovina",
    "Bosnia H.": "Bosnia y Herzegovina",
    "Botsuana": "Botsuana",
    "botsuano": "Botsuana",
    "botsuana": "Botsuana",
    "Brasil": "Brasil",
    "brasileño": "Brasil",
    "brasileña": "Brasil",
    "Brunéi": "Brunéi",
    "bruneano": "Brunéi",
    "bruneana": "Brunéi",
    "Bulgaria": "Bulgaria",
    "búlgaro": "Bulgaria",
    "búlgara": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "burkinés": "Burkina Faso",
    "burkinesa": "Burkina Faso",
    "Burundi": "Burundi",
    "burundés": "Burundi",
    "burundesa": "Burundi",
    "Bután": "Bután",
    "butanés": "Bután",
    "butanesa": "Bután",
    "Cabo Verde": "Cabo Verde",
    "Cabo ver.": "Cabo Verde",
    "caboverdiano": "Cabo Verde",
    "caboverdiana": "Cabo Verde",
    "Camboya": "Camboya",
    "camboyano": "Camboya",
    "camboyana": "Camboya",
    "Camerún": "Camerún",
    "camerunés": "Camerún",
    "camerunesa": "Camerún",
    "Canadá": "Canadá",
    "canadiense": "Canadá",
    "Catar": "Catar",
    "catarí": "Catar",
    "Chad": "Chad",
    "chadiano": "Chad",
    "chadiana": "Chad",
    "Chile": "Chile",
    "chileno": "Chile",
    "chilena": "Chile",
    "China": "China",
    "China Pop.": "China",
    "chino": "China",
    "china": "China",
    "Chipre": "Chipre",
    "chipriota": "Chipre",
    "Ciudad del Vaticano": "Ciudad del Vaticano",
    "vaticano": "Ciudad del Vaticano",
    "vaticana": "Ciudad del Vaticano",
    "Colombia": "Colombia",
    "colombiano": "Colombia",
    "colombiana": "Colombia",
    "Comoras": "Comoras",
    "comorense": "Comoras",
    "Corea del Norte": "Corea del Norte",
    "norcoreano": "Corea del Norte",
    "norcoreana": "Corea del Norte",
    "Corea del Sur": "Corea del Sur",
    "Corea Sur": "Corea del Sur",
    "surcoreano": "Corea del Sur",
    "surcoreana": "Corea del Sur",
    "Costa de Marfil": "Costa de Marfil",
    "marfileño": "Costa de Marfil",
    "marfileña": "Costa de Marfil",
    "Costa Rica": "Costa Rica",
    "costarricense": "Costa Rica",
    "Croacia": "Croacia",
    "croata": "Croacia",
    "Cuba": "Cuba",
    "cubano": "Cuba",
    "cubana": "Cuba",
    "Dinamarca": "Dinamarca",
    "danés": "Dinamarca",
    "danesa": "Dinamarca",
    "Dominica": "Dominica",
    "dominiqués": "Dominica",
    "dominiquesa": "Dominica",
    "Ecuador": "Ecuador",
    "ecuatoriano": "Ecuador",
    "ecuatoriana": "Ecuador",
    "Egipto": "Egipto",
    "egipcio": "Egipto",
    "egipcia": "Egipto",
    "El Salvador": "El Salvador",
    "salvadoreño": "El Salvador",
    "salvadoreña": "El Salvador",
    "Emiratos Árabes Unidos": "Emiratos Árabes Unidos",
    "emiratí": "Emiratos Árabes Unidos",
    "Eritrea": "Eritrea",
    "eritreo": "Eritrea",
    "eritrea": "Eritrea",
    "Eslovaquia": "Eslovaquia",
    "República Eslovaca": "Eslovaquia",
    "eslovaco": "Eslovaquia",
    "eslovaca": "Eslovaquia",
    "Eslovenia": "Eslovenia",
    "esloveno": "Eslovenia",
    "eslovena": "Eslovenia",
    "España": "España",
    "Spain": "España",
    "español": "España",
    "española": "España",
    "Estados Unidos de América": "Estados Unidos",
    "Estados Unidos": "Estados Unidos",
    "estadounidense": "Estados Unidos",
    "EEUU": "Estados Unidos",
    "E.E.U.U.": "Estados Unidos",
    "Estonia": "Estonia",
    "estonio": "Estonia",
    "estonia": "Estonia",
    "Etiopía": "Etiopía",
    "etíope": "Etiopía",
    "Filipinas": "Filipinas",
    "filipino": "Filipinas",
    "filipina": "Filipinas",
    "Finlandia": "Finlandia",
    "finlandés": "Finlandia",
    "finlandesa": "Finlandia",
    "Fiyi": "Fiyi",
    "fiyiano": "Fiyi",
    "fiyiana": "Fiyi",
    "Francia": "Francia",
    "francés": "Francia",
    "francesa": "Francia",
    "Gabón": "Gabón",
    "gabonés": "Gabón",
    "gabonesa": "Gabón",
    "Gambia": "Gambia",
    "gambiano": "Gambia",
    "gambiana": "Gambia",
    "Georgia": "Georgia",
    "georgiano": "Georgia",
    "georgiana": "Georgia",
    "Ghana": "Ghana",
    "ghanés": "Ghana",
    "ghanesa": "Ghana",
    "Granada": "Granada",
    "granadino": "Granada",
    "granadina": "Granada",
    "Grecia": "Grecia",
    "griego": "Grecia",
    "griega": "Grecia",
    "Guatemala": "Guatemala",
    "guatemalteco": "Guatemala",
    "guatemalteca": "Guatemala",
    "Guyana": "Guyana",
    "guyanés": "Guyana",
    "guyanesa": "Guyana",
    "Guinea": "Guinea",
    "guineano": "Guinea",
    "guineana": "Guinea",
    "Guinea ecuatorial": "Guinea ecuatorial",
    "Guinea Ec.": "Guinea ecuatorial",
    "ecuatoguineano": "Guinea ecuatorial",
    "ecuatoguineana": "Guinea ecuatorial",
    "Guinea-Bisáu": "Guinea-Bisáu",
    "bisauguineano": "Guinea-Bisáu",
    "bisauguineana": "Guinea-Bisáu",
    "Guinea Bissau": "Guinea-Bisáu",
    "Haití": "Haití",
    "haitiano": "Haití",
    "haitiana": "Haití",
    "Honduras": "Honduras",
    "hondureño": "Honduras",
    "hondureña": "Honduras",
    "Hungría": "Hungría",
    "húngaro": "Hungría",
    "húngara": "Hungría",
    "India": "India",
    "indio": "India",
    "india": "India",
    "Indonesia": "Indonesia",
    "indonesio": "Indonesia",
    "indonesia": "Indonesia",
    "Irak": "Irak",
    "iraquí": "Irak",
    "Irán": "Irán",
    "iraní": "Irán",
    "Irlanda": "Irlanda",
    "irlandés": "Irlanda",
    "irlandesa": "Irlanda",
    "Islandia": "Islandia",
    "islandés": "Islandia",
    "islandesa": "Islandia",
    "Islas Marshall": "Islas Marshall",
    "marshalés": "Islas Marshall",
    "marshalina": "Islas Marshall",
    "Islas Salomón": "Islas Salomón",
    "salomonense": "Islas Salomón",
    "Israel": "Israel",
    "israelí": "Israel",
    "Italia": "Italia",
    "italiano": "Italia",
    "italiana": "Italia",
    "Jamaica": "Jamaica",
    "jamaicano": "Jamaica",
    "jamaicana": "Jamaica",
    "Japón": "Japón",
    "japonés": "Japón",
    "japonesa": "Japón",
    "Jordania": "Jordania",
    "jordano": "Jordania",
    "jordana": "Jordania",
    "Kazajistán": "Kazajistán",
    "kazajo": "Kazajistán",
    "kazaja": "Kazajistán",
    "Kenia": "Kenia",
    "keniata": "Kenia",
    "Kirguistán": "Kirguistán",
    "kirguís": "Kirguistán",
    "Kiribati": "Kiribati",
    "kiribatiano": "Kiribati",
    "kiribatiana": "Kiribati",
    "Kuwait": "Kuwait",
    "kuwaití": "Kuwait",
    "Laos": "Laos",
    "laosiano": "Laos",
    "laosiana": "Laos",
    "Lesoto": "Lesoto",
    "lesotense": "Lesoto",
    "Letonia": "Letonia",
    "letón": "Letonia",
    "letona": "Letonia",
    "Líbano": "Líbano",
    "libanés": "Líbano",
    "libanesa": "Líbano",
    "Liberia": "Liberia",
    "liberiano": "Liberia",
    "liberiana": "Liberia",
    "Libia": "Libia",
    "libio": "Libia",
    "libia": "Libia",
    "Liechtenstein": "Liechtenstein",
    "liechtensteiniano": "Liechtenstein",
    "liechtensteiniana": "Liechtenstein",
    "Lituania": "Lituania",
    "lituano": "Lituania",
    "lituana": "Lituania",
    "Luxemburgo": "Luxemburgo",
    "luxemburgués": "Luxemburgo",
    "luxemburguesa": "Luxemburgo",
    "Macedonia del Norte": "Macedonia del Norte",
    "macedonio": "Macedonia del Norte",
    "macedonia": "Macedonia del Norte",
    "Madagascar": "Madagascar",
    "malgache": "Madagascar",
    "Malasia": "Malasia",
    "malasio": "Malasia",
    "malasia": "Malasia",
    "Malaui": "Malaui",
    "malauí": "Malaui",
    "Maldivas": "Maldivas",
    "maldivo": "Maldivas",
    "maldiva": "Maldivas",
    "Malí": "Malí",
    "maliense": "Malí",
    "Malta": "Malta",
    "maltés": "Malta",
    "maltesa": "Malta",
    "Marruecos": "Marruecos",
    "marroquí": "Marruecos",
    "Mauricio": "Mauricio",
    "mauriciano": "Mauricio",
    "mauriciana": "Mauricio",
    "Mauritania": "Mauritania",
    "mauritano": "Mauritania",
    "mauritana": "Mauritania",
    "México": "México",
    "Méjico": "México",
    "mexicano": "México",
    "mexicana": "México",
    "Micronesia": "Micronesia",
    "micronesio": "Micronesia",
    "micronesia": "Micronesia",
    "Moldavia": "Moldavia",
    "moldavo": "Moldavia",
    "moldava": "Moldavia",
    "Mónaco": "Mónaco",
    "monegasco": "Mónaco",
    "monegasca": "Mónaco",
    "Mongolia": "Mongolia",
    "mongol": "Mongolia",
    "mongola": "Mongolia",
    "Montenegro": "Montenegro",
    "montenegrino": "Montenegro",
    "montenegrina": "Montenegro",
    "Mozambique": "Mozambique",
    "mozambiqueño": "Mozambique",
    "mozambiqueña": "Mozambique",
    "Namibia": "Namibia",
    "namibio": "Namibia",
    "namibia": "Namibia",
    "Nauru": "Nauru",
    "nauruano": "Nauru",
    "nauruana": "Nauru",
    "Nepal": "Nepal",
    "nepalí": "Nepal",
    "Nicaragua": "Nicaragua",
    "nicaragüense": "Nicaragua",
    "Níger": "Níger",
    "nigerino": "Níger",
    "nigerina": "Níger",
    "Nigeria": "Nigeria",
    "nigeriano": "Nigeria",
    "nigeriana": "Nigeria",
    "Noruega": "Noruega",
    "noruego": "Noruega",
    "noruega": "Noruega",
    "Nueva Zelanda": "Nueva Zelanda",
    "neozelandés": "Nueva Zelanda",
    "neozelandesa": "Nueva Zelanda",
    "Omán": "Omán",
    "omaní": "Omán",
    "Países Bajos": "Países Bajos",
    "P. Bajos": "Países Bajos",
    "neerlandés": "Países Bajos",
    "neerlandesa": "Países Bajos",
    "Pakistán": "Pakistán",
    "paquistaní": "Pakistán",
    "Palaos": "Palaos",
    "palauano": "Palaos",
    "palauana": "Palaos",
    "Palestina": "Palestina",
    "palestino": "Palestina",
    "palestina": "Palestina",
    "Panamá": "Panamá",
    "panameño": "Panamá",
    "panameña": "Panamá",
    "Papúa Nueva Guinea": "Papúa Nueva Guinea",
    "papú": "Papúa Nueva Guinea",
    "Paraguay": "Paraguay",
    "paraguayo": "Paraguay",
    "paraguaya": "Paraguay",
    "Perú": "Perú",
    "peruano": "Perú",
    "peruana": "Perú",
    "Polonia": "Polonia",
    "polaco": "Polonia",
    "polaca": "Polonia",
    "Portugal": "Portugal",
    "portugués": "Portugal",
    "portuguesa": "Portugal",
    "Reino Unido": "Reino Unido",
    "británico": "Reino Unido",
    "británica": "Reino Unido",
    "Gran Bretaña": "Reino Unido",
    "G. Bretaña": "Reino Unido",
    "República Centroafricana": "República Centroafricana",
    "Rep. Centroafricana": "República Centroafricana",
    "centroafricano": "República Centroafricana",
    "centroafricana": "República Centroafricana",
    "República Checa": "República Checa",
    "R.Checa": "República Checa",
    "checo": "República Checa",
    "checa": "República Checa",
    "República del Congo": "República del Congo",
    "Congo": "República del Congo",
    "República Democrática del Congo": "República Democrática del Congo",
    "Rep. Dem. del Congo": "República Democrática del Congo",
    "República Dominicana": "República Dominicana",
    "Rep.Dominicana": "República Dominicana",
    "dominicano": "República Dominicana",
    "dominicana": "República Dominicana",
    "Ruanda": "Ruanda",
    "ruandés": "Ruanda",
    "ruandesa": "Ruanda",
    "Rumanía": "Rumanía",
    "rumano": "Rumanía",
    "rumana": "Rumanía",
    "Rusia": "Rusia",
    "ruso": "Rusia",
    "rusa": "Rusia",
    "Samoa": "Samoa",
    "Sahara Occidental": "Sahara Occidental",
    "saharaui": "Sahara Occidental",
    "Sahara": "Sahara Occidental",
    "samoano": "Samoa",
    "samoana": "Samoa",
    "San Cristóbal y Nieves": "San Cristóbal y Nieves",
    "sancristobaleño": "San Cristóbal y Nieves",
    "sancristobaleña": "San Cristóbal y Nieves",
    "San Marino": "San Marino",
    "sanmarinense": "San Marino",
    "San Vicente y las Granadinas": "San Vicente y las Granadinas",
    "sanvicentino": "San Vicente y las Granadinas",
    "sanvicentina": "San Vicente y las Granadinas",
    "Santa Lucía": "Santa Lucía",
    "santalucense": "Santa Lucía",
    "Santo Tomé y Príncipe": "Santo Tomé y Príncipe",
    "santotomense": "Santo Tomé y Príncipe",
    "Senegal": "Senegal",
    "senegalés": "Senegal",
    "senegalesa": "Senegal",
    "Serbia": "Serbia",
    "serbio": "Serbia",
    "serbia": "Serbia",
    "Seychelles": "Seychelles",
    "seychellense": "Seychelles",
    "Sierra Leona": "Sierra Leona",
    "sierraleonés": "Sierra Leona",
    "sierraleonesa": "Sierra Leona",
    "Singapur": "Singapur",
    "singapurense": "Singapur",
    "Siria": "Siria",
    "sirio": "Siria",
    "siria": "Siria",
    "Somalia": "Somalia",
    "somalí": "Somalia",
    "Sri Lanka": "Sri Lanka",
    "ceilandés": "Sri Lanka",
    "ceilandesa": "Sri Lanka",
    "Suazilandia": "Suazilandia",
    "suazi": "Suazilandia",
    "Sudáfrica": "Sudáfrica",
    "sudafricano": "Sudáfrica",
    "sudafricana": "Sudáfrica",
    "Sudán": "Sudán",
    "sudanés": "Sudán",
    "sudanesa": "Sudán",
    "Sudán del Sur": "Sudán del Sur",
    "sursudanés": "Sudán del Sur",
    "sursudanesa": "Sudán del Sur",
    "Suecia": "Suecia",
    "sueco": "Suecia",
    "sueca": "Suecia",
    "Suiza": "Suiza",
    "suizo": "Suiza",
    "suiza": "Suiza",
    "Surinam": "Surinam",
    "surinamés": "Surinam",
    "surinamesa": "Surinam",
    "Tailandia": "Tailandia",
    "Thailandia": "Tailandia",
    "tailandés": "Tailandia",
    "tailandesa": "Tailandia",
    "Taiwán": "Taiwán",
    "taiwanés": "Taiwán",
    "taiwanesa": "Taiwán",
    "Tanzania": "Tanzania",
    "tanzano": "Tanzania",
    "tanzana": "Tanzania",
    "Tayikistán": "Tayikistán",
    "tayiko": "Tayikistán",
    "tayika": "Tayikistán",
    "Timor Oriental": "Timor Oriental",
    "timorense": "Timor Oriental",
    "Togo": "Togo",
    "togolés": "Togo",
    "togolesa": "Togo",
    "Tonga": "Tonga",
    "tongano": "Tonga",
    "tongana": "Tonga",
    "Trinidad y Tobago": "Trinidad y Tobago",
    "trinitense": "Trinidad y Tobago",
    "Túnez": "Túnez",
    "tunecino": "Túnez",
    "tunecina": "Túnez",
    "Turkmenistán": "Turkmenistán",
    "turcomano": "Turkmenistán",
    "turcomana": "Turkmenistán",
    "Turquía": "Turquía",
    "turco": "Turquía",
    "turca": "Turquía",
    "Tuvalu": "Tuvalu",
    "tuvaluano": "Tuvalu",
    "tuvaluana": "Tuvalu",
    "Ucrania": "Ucrania",
    "ucraniano": "Ucrania",
    "ucraniana": "Ucrania",
    "Uganda": "Uganda",
    "ugandés": "Uganda",
    "ugandesa": "Uganda",
    "Uruguay": "Uruguay",
    "uruguayo": "Uruguay",
    "uruguaya": "Uruguay",
    "Uzbekistán": "Uzbekistán",
    "uzbeko": "Uzbekistán",
    "uzbeka": "Uzbekistán",
    "Vanuatu": "Vanuatu",
    "vanuatuense": "Vanuatu",
    "Venezuela": "Venezuela",
    "venezolano": "Venezuela",
    "venezolana": "Venezuela",
    "Vietnam": "Vietnam",
    "vietnamita": "Vietnam",
    "Yemen": "Yemen",
    "yemení": "Yemen",
    "Yibuti": "Yibuti",
    "yibutiano": "Yibuti",
    "yibutiana": "Yibuti",
    "Yugoslavia": "Yugoslavia",
    "Yugoslav.r": "Yugoslavia",
    "yugoslavo": "Yugoslavia",
    "yugoslava": "Yugoslavia",
    "Zambia": "Zambia",
    "zambiano": "Zambia",
    "zambiana": "Zambia",
    "Zimbabue": "Zimbabue",
    "zimbabuense": "Zimbabue",
}
